// Copies the verified Quiet Bands vectors from the site's assets/brand/ into a typed module the
// renderer can draw inline. The SVG files stay the single source of truth: this script never
// edits them, and tests/brand.test.ts fails if the generated module drifts from them.
import {readFileSync, writeFileSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const BRAND_DIR = path.resolve(HERE, '../../assets/brand');
export const GENERATED = path.resolve(HERE, '../src/themes/quiet-bands/brand.generated.ts');

export interface VectorPath {
  d: string;
  transform?: string;
}
export interface Vector {
  file: string;
  viewBox: [number, number, number, number];
  paths: VectorPath[];
}

export function parseSvg(file: string, svg: string): Vector {
  const vb = svg.match(/viewBox="([^"]+)"/);
  if (!vb) throw new Error(`${file}: no viewBox`);
  const viewBox = vb[1].trim().split(/[\s,]+/).map(Number) as Vector['viewBox'];
  const paths: VectorPath[] = [];
  for (const m of svg.matchAll(/<path\b([^>]*)\/?>/g)) {
    const attrs = m[1];
    const d = attrs.match(/\bd="([^"]+)"/)?.[1];
    if (!d) continue;
    const transform = attrs.match(/\btransform="([^"]+)"/)?.[1];
    paths.push(transform ? {d, transform} : {d});
  }
  if (!paths.length) throw new Error(`${file}: no paths`);
  return {file, viewBox, paths};
}

export function readBrand(): Record<'mark' | 'wordmark' | 'lockup', Vector> {
  const read = (name: string) => parseSvg(`assets/brand/${name}.svg`, readFileSync(path.join(BRAND_DIR, `${name}.svg`), 'utf8'));
  return {mark: read('mark'), wordmark: read('wordmark'), lockup: read('lockup')};
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const brand = readBrand();
  const body = `// GENERATED by scripts/sync-brand.ts from the site's assets/brand/*.svg. Do not edit.
// Run \`npm run sync:brand\` after the brand files change; tests/brand.test.ts checks parity.
export interface BrandVector {
  file: string;
  viewBox: [number, number, number, number];
  paths: {d: string; transform?: string}[];
}

export const BRAND: Record<'mark' | 'wordmark' | 'lockup', BrandVector> = ${JSON.stringify(brand, null, 2)};
`;
  writeFileSync(GENERATED, body);
  console.log(`wrote ${path.relative(process.cwd(), GENERATED)} (${Object.keys(brand).join(', ')})`);
}
